apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext51
  labels:
    app: BoundedContext51
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext51
  template:
    metadata:
      labels:
        app: BoundedContext51
    spec:
      containers:
        - name: BoundedContext51
          image: username/BoundedContext51:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
